### ISSUE TITLE
Published version of this SDK is not updated

### ISSUE THREAD

**Issue by siyant** [EnvisionIot/enos-device-sdk-python#2]
There seems to be a mismatch between the [published version of this package on pypi (0.0.4)](https://pypi.org/project/enos-api-sdk-python/) and this code (0.1.0). I'm guessing that this package was renamed from enos-api-sdk-python to the current enos-device-sdk-python, but the project published on pypi still links to "https://github.com/EnvisionIot/enos-api-sdk-python" (gives a 404) as its homepage.

Also I don't know if there is a mixup between this repo and the MQTT one - the readme of this repo says to install using

`pip install enos-mqtt-sdk-python`

It is quite confusing currently. Some clarification would be helpful please!

**Comment by jieyuan-shen** [comment]
Hi, siyant
You are mentioning two different SDKs. 
This repo is for Device SDK, to enable devices connecting to EnOS via MQTT. It's pypi location is : https://pypi.org/project/enos-mqtt-sdk-python/    (current version 0.1.0)

The API SDK ( https://pypi.org/project/enos-api-sdk-python/) is to enable APPs to invoke EnOS Open APIs. 

So they are two different SDKs.

And I realized there is no public REPO for API SDK. We will fix it asap. Thanks for your feedback.

**Comment by siyant** [comment]
Hi Jieyuan, thanks for your explanation! I get it now.

Just to check one more thing- what's the difference between https://github.com/EnvisionIot/enos-mqtt-sdk-python and this repo?

**Comment by jieyuan-shen** [comment]
Hi, siyant

 https://github.com/EnvisionIot/enos-mqtt-sdk-python  is the repo for old code, we will archive it soon.

For the latest code, please refer to  https://github.com/EnvisionIot/enos-device-sdk-python

The link in PyPi description is not correct as well. We will fix the PyPi description next release.

**Comment by jieyuan-shen** [comment]
@charleshuangcai  pls fix the link in PyPi description
